/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotauthedImport } from './routes/_not_authed'
import { Route as AuthedImport } from './routes/_authed'

// Create Virtual Routes

const SplatLazyImport = createFileRoute('/$')()
const AuthedIndexLazyImport = createFileRoute('/_authed/')()
const NotauthedSignupLazyImport = createFileRoute('/_not_authed/signup')()
const NotauthedLoginLazyImport = createFileRoute('/_not_authed/login')()
const AuthedUserSettingsLazyImport = createFileRoute('/_authed/user-settings')()

// Create/Update Routes

const SplatLazyRoute = SplatLazyImport.update({
  path: '/$',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$.lazy').then((d) => d.Route))

const NotauthedRoute = NotauthedImport.update({
  id: '/_not_authed',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const AuthedIndexLazyRoute = AuthedIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() => import('./routes/_authed/index.lazy').then((d) => d.Route))

const NotauthedSignupLazyRoute = NotauthedSignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => NotauthedRoute,
} as any).lazy(() =>
  import('./routes/_not_authed/signup.lazy').then((d) => d.Route),
)

const NotauthedLoginLazyRoute = NotauthedLoginLazyImport.update({
  path: '/login',
  getParentRoute: () => NotauthedRoute,
} as any).lazy(() =>
  import('./routes/_not_authed/login.lazy').then((d) => d.Route),
)

const AuthedUserSettingsLazyRoute = AuthedUserSettingsLazyImport.update({
  path: '/user-settings',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/user-settings.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_not_authed': {
      id: '/_not_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NotauthedImport
      parentRoute: typeof rootRoute
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authed/user-settings': {
      id: '/_authed/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof AuthedUserSettingsLazyImport
      parentRoute: typeof AuthedImport
    }
    '/_not_authed/login': {
      id: '/_not_authed/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NotauthedLoginLazyImport
      parentRoute: typeof NotauthedImport
    }
    '/_not_authed/signup': {
      id: '/_not_authed/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof NotauthedSignupLazyImport
      parentRoute: typeof NotauthedImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexLazyImport
      parentRoute: typeof AuthedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthedRoute: AuthedRoute.addChildren({
    AuthedUserSettingsLazyRoute,
    AuthedIndexLazyRoute,
  }),
  NotauthedRoute: NotauthedRoute.addChildren({
    NotauthedLoginLazyRoute,
    NotauthedSignupLazyRoute,
  }),
  SplatLazyRoute,
})

/* prettier-ignore-end */
